"""Attack Chain Narrator — AI-powered exploitation narrative generation.

Takes attack chain data and produces natural-language pentester-style
writeups using any configured LLM provider.
"""
from __future__ import annotations

import logging
from typing import Any

from scoutx.ai.client import LLMClient

logger = logging.getLogger("scoutx.chains.narrator")

SYSTEM_PROMPT = """You are a senior penetration tester writing a reconnaissance report.
Your task is to narrate attack chains discovered during automated recon.

Write in first-person, technical but clear prose. For each chain:
1. Describe what was found and why it matters
2. Walk through the exploitation path step by step
3. Include specific evidence from the scan data (hostnames, ports, headers, etc.)
4. Assess the real-world impact if exploited
5. Provide actionable remediation recommendations

Keep it professional. Use markdown formatting with headers, code blocks, and bullet points.
Do NOT add disclaimers — this is an authorized assessment report."""


class ChainNarrator:
    """Generate natural-language attack narratives from chain data."""

    def __init__(self, client: LLMClient):
        self.client = client

    async def narrate_report(self, chain_report: dict[str, Any]) -> str:
        """Narrate an entire chain report with multiple chains."""
        chains = chain_report.get("chains", [])
        if not chains:
            return ""

        target = chain_report.get("target", "unknown")
        sections = [f"# Attack Chain Narrative — {target}\n"]
        sections.append(f"*Generated by ScoutX AI ({self.client.provider_name()})*\n")

        for i, chain in enumerate(chains, 1):
            narrative = await self.narrate_chain(chain, i)
            if narrative:
                sections.append(narrative)
            else:
                # Fallback: structured output without AI
                sections.append(self._fallback_narration(chain, i))

        return "\n---\n\n".join(sections)

    async def narrate_chain(self, chain: dict[str, Any], index: int = 1) -> str:
        """Narrate a single attack chain."""
        prompt = self._build_chain_prompt(chain, index)

        try:
            result = await self.client.generate(
                prompt=prompt,
                system_prompt=SYSTEM_PROMPT,
                max_tokens=2048,
            )
            return result if result.strip() else ""
        except Exception:
            logger.warning(f"AI narration failed for chain {index}, using fallback")
            return ""

    def _build_chain_prompt(self, chain: dict[str, Any], index: int) -> str:
        """Build the prompt from chain data."""
        lines = [f"Narrate attack chain #{index}:\n"]

        lines.append(f"**Chain Type:** {chain.get('chain_type', 'unknown')}")
        lines.append(f"**Title:** {chain.get('title', 'Untitled')}")
        lines.append(f"**Severity:** {chain.get('severity', 'unknown')}")
        lines.append(f"**Risk Score:** {chain.get('risk_score', 0)}/100")

        steps = chain.get("steps", [])
        if steps:
            lines.append("\n**Exploitation Steps:**")
            for j, step in enumerate(steps, 1):
                phase = step.get("phase", "")
                desc = step.get("description", "")
                tool = step.get("tool", "")
                evidence = step.get("evidence", "")
                lines.append(f"{j}. [{phase}] {desc}")
                if tool:
                    lines.append(f"   Tool: {tool}")
                if evidence:
                    lines.append(f"   Evidence: {evidence}")

        impact = chain.get("impact", "")
        if impact:
            lines.append(f"\n**Impact:** {impact}")

        affected = chain.get("affected_hosts", [])
        if affected:
            lines.append(f"\n**Affected Hosts:** {', '.join(affected[:10])}")

        return "\n".join(lines)

    def _fallback_narration(self, chain: dict[str, Any], index: int) -> str:
        """Structured output when AI is unavailable."""
        lines = [f"## Chain {index}: {chain.get('title', 'Untitled')}\n"]
        lines.append(f"**Type:** {chain.get('chain_type', 'unknown')}")
        lines.append(f"**Severity:** {chain.get('severity', 'unknown')}")
        lines.append(f"**Risk Score:** {chain.get('risk_score', 0)}/100\n")

        steps = chain.get("steps", [])
        if steps:
            lines.append("### Exploitation Path\n")
            for j, step in enumerate(steps, 1):
                lines.append(f"{j}. **{step.get('phase', '')}** — {step.get('description', '')}")

        impact = chain.get("impact", "")
        if impact:
            lines.append(f"\n### Impact\n{impact}")

        remediation = chain.get("remediation", "")
        if remediation:
            lines.append(f"\n### Remediation\n{remediation}")

        return "\n".join(lines)
