"""Attack Chain Report Generators — MD, HTML, and JSON output.

Turns ChainReport objects into beautiful, actionable documents
that a penetration tester can follow step by step.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from scoutx.chains.models import ChainReport, ChecklistItem

logger = logging.getLogger("scoutx.chains.reporter")


class ChainReporter:
    """Generate attack chain reports in multiple formats."""

    def __init__(self, report: ChainReport) -> None:
        self._report = report

    def write_all(self, output_dir: Path) -> list[Path]:
        """Write all report formats to the output directory."""
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        paths.append(self.write_markdown(output_dir / "attack_playbook.md"))
        paths.append(self.write_json(output_dir / "attack_chains.json"))
        paths.append(self.write_html(output_dir / "attack_playbook.html"))
        paths.append(self.write_checklist(output_dir / "vuln_checklist.md"))
        return paths

    # ------------------------------------------------------------------
    # Markdown
    # ------------------------------------------------------------------
    def write_markdown(self, path: Path) -> Path:
        """Write a detailed, actionable attack playbook for pentesters."""
        r = self._report
        lines: list[str] = []
        sev = r.severity_counts()
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines.append(f"# 🎯 Attack Playbook: {r.target}")
        lines.append(f"\n> Generated by ScoutX Attack Chain Engine | {ts}")
        lines.append("> **PURPOSE:** Test each finding below to confirm if it's a real, exploitable vulnerability")
        lines.append("> before including it in your report. Follow the validation steps — don't submit informational noise.")
        lines.append("\n## Dashboard\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Attack Chains | **{len(r.chains)}** |")
        lines.append(f"| 🔴 Critical | {sev.get('critical', 0)} |")
        lines.append(f"| 🟠 High | {sev.get('high', 0)} |")
        lines.append(f"| 🟡 Medium | {sev.get('medium', 0)} |")
        lines.append(f"| 🟢 Low / Info | {sev.get('low', 0)} |")
        lines.append(f"| Checklist Coverage | {len(r.applicable_checks)}/{len(r.checklist)} applicable |")

        if r.chains:
            lines.append("\n---\n")
            lines.append("## Attack Chains\n")

        for i, chain in enumerate(r.chains, 1):
            sev_emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(chain.severity, "⚪")
            lines.append(f"### {sev_emoji} Chain #{i}: [{chain.severity.upper()}] {chain.title}")
            lines.append("\n| Field | Value |")
            lines.append("|-------|-------|")
            lines.append(f"| Confidence | **{chain.confidence:.0%}** |")
            lines.append(f"| Category | {chain.category} |")
            if chain.cvss_score:
                lines.append(f"| CVSS | {chain.cvss_score} |")
            if chain.target_host:
                lines.append(f"| Target | `{chain.target_host}` |")

            lines.append("\n#### What Is This?")
            lines.append(f"\n{chain.description}")

            if chain.affected_assets:
                lines.append("\n#### Affected Assets")
                for a in chain.affected_assets[:10]:
                    lines.append(f"- `{a}`")

            if chain.prerequisites:
                lines.append("\n#### Prerequisites (What must be true)")
                for p in chain.prerequisites:
                    lines.append(f"- {p}")

            # The meat — step by step exploitation
            lines.append("\n#### 🔬 Step-by-Step Exploitation & Validation\n")
            lines.append("> Follow these steps IN ORDER. Each step builds on the previous one.")
            lines.append("> If any step fails, the chain is likely **not exploitable** — mark as informational.\n")

            for step in chain.steps:
                lines.append(f"**Step {step.order}: {step.action}**\n")
                lines.append("```bash")
                lines.append(f"{step.command}")
                lines.append("```\n")
                lines.append(f"✅ **Expected if vulnerable:** {step.expected_result}")
                if step.notes:
                    lines.append(f"\n💡 **Note:** {step.notes}")
                lines.append("")

            # Is this real?
            lines.append("#### ⚖️ Is This Real or Informational?\n")
            _triage = _get_triage_guidance(chain)
            lines.append("| Question | If YES → | If NO → |")
            lines.append("|----------|----------|---------|")
            for q, yes, no in _triage:
                lines.append(f"| {q} | {yes} | {no} |")

            # Before you submit
            lines.append("\n#### 📋 Before You Submit\n")
            lines.append("- [ ] Completed all validation steps above")
            lines.append("- [ ] Captured screenshots/responses as evidence")
            lines.append("- [ ] Confirmed this is **not** a false positive")
            lines.append("- [ ] Impact is clear (what can an attacker DO with this?)")
            lines.append("- [ ] Wrote reproduction steps someone else can follow")

            if chain.mitigation:
                lines.append("\n#### 🛡️ Remediation\n")
                lines.append(f"{chain.mitigation}")

            if chain.tools_needed:
                lines.append(f"\n**Tools needed:** `{', '.join(chain.tools_needed)}`")

            if chain.references:
                lines.append("\n#### References")
                for ref in chain.references:
                    lines.append(f"- {ref}")
            lines.append("\n---\n")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Markdown playbook written to %s", path)
        return path

    # ------------------------------------------------------------------
    # JSON
    # ------------------------------------------------------------------
    def write_json(self, path: Path) -> Path:
        """Write JSON report."""
        data = self._report.to_dict()
        path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
        logger.info("JSON report written to %s", path)
        return path

    # ------------------------------------------------------------------
    # Checklist Markdown
    # ------------------------------------------------------------------
    def write_checklist(self, path: Path) -> Path:
        """Write the vulnerability checklist as markdown."""
        r = self._report
        lines: list[str] = []
        lines.append(f"# Vulnerability Checklist: {r.target}")
        lines.append(f"\n> {len(r.applicable_checks)}/{len(r.checklist)} checks applicable based on recon findings\n")

        # Group by phase
        phases: dict[str, list[ChecklistItem]] = {}
        for item in r.checklist:
            if item.phase not in phases:
                phases[item.phase] = []
            phases[item.phase].append(item)

        for phase, items in phases.items():
            applicable = [i for i in items if i.applicable]
            lines.append(f"## {phase} ({len(applicable)}/{len(items)} applicable)")
            lines.append("")
            for item in items:
                mark = "x" if item.applicable else " "
                sev_tag = f"[{item.severity.upper()[0]}]"
                lines.append(f"- [{mark}] {sev_tag} {item.check}")
                if item.applicable and item.reason:
                    lines.append(f"  - *{item.reason}*")
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Checklist written to %s", path)
        return path

    # ------------------------------------------------------------------
    # HTML
    # ------------------------------------------------------------------
    def write_html(self, path: Path) -> Path:
        """Write a dark-themed HTML attack playbook."""
        r = self._report
        sev = r.severity_counts()
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        chains_html = []
        for i, chain in enumerate(r.chains, 1):
            sev_class = chain.severity
            # Build step blocks with full commands
            steps_html = ""
            for s in chain.steps:
                note_html = f'<p class="step-note">💡 {_esc(s.notes)}</p>' if s.notes else ""
                steps_html += f"""
                <div class="step-block">
                    <div class="step-header">Step {s.order}: {_esc(s.action)}</div>
                    <pre class="step-cmd">{_esc(s.command)}</pre>
                    <p class="step-expect">✅ <strong>Expected if vulnerable:</strong> {_esc(s.expected_result)}</p>
                    {note_html}
                </div>"""

            assets = "".join(f"<li><code>{_esc(a)}</code></li>" for a in chain.affected_assets[:10])
            refs = "".join(f'<li><a href="{ref}" target="_blank">{_esc(ref[:80])}</a></li>' for ref in chain.references)

            # Build triage table
            triage = _get_triage_guidance(chain)
            triage_rows = "".join(
                f"<tr><td>{_esc(q)}</td><td>{yes}</td><td>{no}</td></tr>"
                for q, yes, no in triage
            )

            chains_html.append(f"""
            <div class="chain {sev_class}">
                <div class="chain-header">
                    <span class="chain-num">#{i}</span>
                    <span class="sev-badge {sev_class}">{chain.severity.upper()}</span>
                    <h3>{_esc(chain.title)}</h3>
                    <span class="confidence">{chain.confidence:.0%} confidence</span>
                </div>
                <p class="desc">{_esc(chain.description)}</p>
                <div class="assets"><strong>Affected:</strong><ul>{assets}</ul></div>

                <h4>🔬 Step-by-Step Exploitation & Validation</h4>
                <p class="desc">Follow each step in order. If any step fails, the chain is likely <strong>not exploitable</strong> — mark as informational.</p>
                {steps_html}

                <h4>⚖️ Is This Real or Informational?</h4>
                <table class="triage">
                    <thead><tr><th>Question</th><th>If YES →</th><th>If NO →</th></tr></thead>
                    <tbody>{triage_rows}</tbody>
                </table>

                <h4>📋 Before You Submit</h4>
                <ul class="checklist">
                    <li>☐ Completed all validation steps above</li>
                    <li>☐ Captured screenshots/responses as evidence</li>
                    <li>☐ Confirmed this is <strong>not</strong> a false positive</li>
                    <li>☐ Impact is clear (what can an attacker DO with this?)</li>
                    <li>☐ Wrote reproduction steps someone else can follow</li>
                </ul>

                <div class="meta">
                    <p><strong>Tools:</strong> {', '.join(chain.tools_needed)}</p>
                    <p><strong>Mitigation:</strong> {_esc(chain.mitigation)}</p>
                    {"<p><strong>References:</strong></p><ul>" + refs + "</ul>" if refs else ""}
                </div>
            </div>""")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Attack Playbook - {_esc(r.target)}</title>
<style>
:root {{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#e6edf3;--muted:#8b949e;
--crit:#f85149;--high:#d29922;--med:#58a6ff;--low:#3fb950;}}
*{{margin:0;padding:0;box-sizing:border-box;}}
body{{background:var(--bg);color:var(--text);font-family:Inter,-apple-system,sans-serif;padding:2rem;}}
h1{{font-size:2rem;margin-bottom:.5rem;}}
.summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:1rem;margin:1.5rem 0;}}
.stat{{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem;text-align:center;}}
.stat .num{{font-size:2rem;font-weight:700;}}
.stat.critical .num{{color:var(--crit);}} .stat.high .num{{color:var(--high);}}
.stat.medium .num{{color:var(--med);}} .stat.low .num{{color:var(--low);}}
.chain{{background:var(--card);border:1px solid var(--border);border-radius:8px;margin:1.5rem 0;padding:1.5rem;}}
.chain.critical{{border-left:4px solid var(--crit);}} .chain.high{{border-left:4px solid var(--high);}}
.chain.medium{{border-left:4px solid var(--med);}} .chain.low{{border-left:4px solid var(--low);}}
.chain-header{{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap;margin-bottom:1rem;}}
.chain-num{{color:var(--muted);font-size:.9rem;}}
.sev-badge{{padding:2px 8px;border-radius:4px;font-size:.75rem;font-weight:700;color:#fff;}}
.sev-badge.critical{{background:var(--crit);}} .sev-badge.high{{background:var(--high);}}
.sev-badge.medium{{background:var(--med);}} .sev-badge.low{{background:var(--low);}}
.chain-header h3{{flex:1;font-size:1.1rem;}}
.confidence{{color:var(--muted);font-size:.85rem;}}
.desc{{color:var(--muted);margin-bottom:1rem;line-height:1.5;}}
h4{{margin:1.5rem 0 .75rem;font-size:1rem;color:var(--text);}}
.step-block{{background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:1rem;margin:.75rem 0;}}
.step-header{{font-weight:700;font-size:.95rem;margin-bottom:.5rem;color:var(--text);}}
.step-cmd{{background:#1c2128;color:#e6edf3;padding:.75rem 1rem;border-radius:4px;font-family:'Fira Code',Consolas,monospace;font-size:.8rem;overflow-x:auto;white-space:pre-wrap;word-break:break-all;margin:.5rem 0;}}
.step-expect{{font-size:.85rem;color:var(--low);margin:.3rem 0;}}
.step-note{{font-size:.8rem;color:var(--high);margin:.3rem 0;}}
.triage{{width:100%;border-collapse:collapse;margin:1rem 0;}}
.triage th,.triage td{{padding:.5rem .75rem;text-align:left;border-bottom:1px solid var(--border);font-size:.85rem;}}
.triage th{{color:var(--muted);font-weight:600;}}
.checklist{{list-style:none;margin:1rem 0;}}
.checklist li{{padding:.3rem 0;font-size:.85rem;color:var(--muted);}}
.meta{{color:var(--muted);font-size:.85rem;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--border);}}
.meta p{{margin:.3rem 0;}} .meta a{{color:var(--med);}}
.assets ul{{list-style:none;display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.3rem;}}
.assets li{{background:var(--bg);padding:2px 8px;border-radius:4px;font-size:.8rem;}}
.footer{{margin-top:2rem;padding-top:1rem;border-top:1px solid var(--border);color:var(--muted);font-size:.8rem;}}
</style>
</head>
<body>
<h1>Attack Playbook: {_esc(r.target)}</h1>
<p style="color:var(--muted);">Generated by ScoutX Attack Chain Engine | {ts}</p>
<div class="summary">
    <div class="stat"><div class="num">{len(r.chains)}</div><div>Total Chains</div></div>
    <div class="stat critical"><div class="num">{sev.get('critical',0)}</div><div>Critical</div></div>
    <div class="stat high"><div class="num">{sev.get('high',0)}</div><div>High</div></div>
    <div class="stat medium"><div class="num">{sev.get('medium',0)}</div><div>Medium</div></div>
    <div class="stat low"><div class="num">{sev.get('low',0)}</div><div>Low</div></div>
    <div class="stat"><div class="num">{len(r.applicable_checks)}/{len(r.checklist)}</div><div>Checklist</div></div>
</div>
{"".join(chains_html)}
<div class="footer">ScoutX v2.0 | Attack Chain Engine | {ts}</div>
</body></html>"""

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8")
        logger.info("HTML playbook written to %s", path)
        return path


def _esc(text: str) -> str:
    """HTML-escape a string."""
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def _get_triage_guidance(chain) -> list[tuple[str, str, str]]:
    """Generate real-vs-informational triage questions per chain category.

    Returns list of (question, if_yes, if_no) tuples.
    """
    cat = chain.category.lower()

    if cat == "credential_exposure":
        return [
            ("Does the secret look like a real key/token (not a placeholder)?",
             "**Likely real** — validate against the service",
             "Probably a template/example — **informational**"),
            ("Can you authenticate to a service with it?",
             "**Confirmed exploitable** — report as HIGH/CRITICAL",
             "Key might be revoked/expired — lower severity"),
            ("Does the key have write/admin permissions?",
             "**Critical** — full account compromise",
             "Read-only access — still report but lower impact"),
            ("Is the secret in a production JS bundle (not test/staging)?",
             "**Production exposure** — needs immediate rotation",
             "Test environment — still report but note the scope"),
        ]
    elif cat == "takeover":
        return [
            ("Does the CNAME still resolve to a claimable service?",
             "**Exploitable** — you can claim and serve content",
             "CNAME removed or reclaimed — **false positive**"),
            ("Can you actually register the service?",
             "**Confirmed** — demonstrate with benign PoC page",
             "Service requires org verification — lower confidence"),
            ("Does the parent domain set cookies on this subdomain?",
             "**Session hijack risk** — escalate to CRITICAL",
             "No cookie scope — still HIGH for phishing"),
        ]
    elif cat == "data_exfil":
        return [
            ("Can you connect without authentication?",
             "**Confirmed** — unauthenticated access to data",
             "Auth required — still report exposed port as MEDIUM"),
            ("Does the service contain sensitive data?",
             "**Critical** — PII/credentials exposed",
             "Empty/test data — lower to informational"),
            ("Is the port accessible from the internet (not just LAN)?",
             "**Internet-exposed** — report as HIGH+",
             "Internal only — note in report, lower severity"),
        ]
    elif cat in ("rce", "vulnerability"):
        return [
            ("Did the PoC command produce the expected output?",
             "**Confirmed RCE/vuln** — report immediately",
             "Patched or mitigated — try alternate payloads"),
            ("Is the target running the vulnerable version?",
             "**Version match** — high likelihood of exploitation",
             "Different version — may be patched, test anyway"),
            ("Can you demonstrate impact (file read, command exec)?",
             "**Full proof** — include output in report",
             "Blind/time-based only — still valid but note limitations"),
        ]
    elif "cors" in cat or "auth" in cat:
        return [
            ("Does the CORS response include credentials: true?",
             "**Exploitable** — cross-origin credential theft possible",
             "No credentials header — limited impact, note as info"),
            ("Does the endpoint return sensitive data?",
             "**Real impact** — user data can be exfiltrated",
             "Public data only — **informational**"),
        ]
    else:
        return [
            ("Can you reproduce the finding manually?",
             "**Confirmed** — document reproduction steps",
             "Might be scanner noise — **verify before reporting**"),
            ("Does exploiting this give unauthorized access or data?",
             "**Real vulnerability** — determine severity by impact",
             "No clear impact — classify as **informational**"),
            ("Would a reasonable developer consider this a bug?",
             "**Report it** — include suggested remediation",
             "Likely intended behavior — skip or note as low"),
        ]
