"""Attack Chain Report Generators — MD, HTML, and JSON output.

Turns ChainReport objects into beautiful, actionable documents
that a penetration tester can follow step by step.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from scoutx.chains.models import ChainReport, ChecklistItem

logger = logging.getLogger("scoutx.chains.reporter")


class ChainReporter:
    """Generate attack chain reports in multiple formats."""

    def __init__(self, report: ChainReport) -> None:
        self._report = report

    def write_all(self, output_dir: Path) -> list[Path]:
        """Write all report formats to the output directory."""
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        paths.append(self.write_markdown(output_dir / "attack_playbook.md"))
        paths.append(self.write_json(output_dir / "attack_chains.json"))
        paths.append(self.write_html(output_dir / "attack_playbook.html"))
        paths.append(self.write_checklist(output_dir / "vuln_checklist.md"))
        return paths

    # ------------------------------------------------------------------
    # Markdown
    # ------------------------------------------------------------------
    def write_markdown(self, path: Path) -> Path:
        """Write a markdown attack playbook."""
        r = self._report
        lines: list[str] = []
        sev = r.severity_counts()
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines.append(f"# Attack Playbook: {r.target}")
        lines.append(f"\n> Generated by ScoutX Attack Chain Engine | {ts}")
        lines.append("\n## Summary")
        lines.append("\n| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total Chains | {len(r.chains)} |")
        lines.append(f"| Critical | {sev.get('critical', 0)} |")
        lines.append(f"| High | {sev.get('high', 0)} |")
        lines.append(f"| Medium | {sev.get('medium', 0)} |")
        lines.append(f"| Low | {sev.get('low', 0)} |")
        lines.append(f"| Applicable Checks | {len(r.applicable_checks)}/{len(r.checklist)} |")

        if r.chains:
            lines.append("\n---\n")
            lines.append("## Attack Chains\n")

        for i, chain in enumerate(r.chains, 1):
            {"critical": "!!!", "high": "!!", "medium": "!", "low": "~"}.get(chain.severity, "")
            lines.append(f"### {i}. [{chain.severity.upper()}] {chain.title}")
            lines.append(f"\n**Confidence:** {chain.confidence:.0%} | **Category:** {chain.category}")
            lines.append(f"\n{chain.description}")

            if chain.prerequisites:
                lines.append("\n**Prerequisites:**")
                for p in chain.prerequisites:
                    lines.append(f"- {p}")

            if chain.affected_assets:
                lines.append("\n**Affected Assets:**")
                for a in chain.affected_assets[:5]:
                    lines.append(f"- `{a}`")

            lines.append("\n**Steps:**\n")
            lines.append("| # | Action | Command | Expected Result |")
            lines.append("|---|--------|---------|-----------------|")
            for step in chain.steps:
                cmd = step.command.replace("|", "\\|").replace("\n", " ")[:80]
                lines.append(f"| {step.order} | {step.action} | `{cmd}` | {step.expected_result} |")

            if chain.tools_needed:
                lines.append(f"\n**Tools:** {', '.join(chain.tools_needed)}")
            if chain.mitigation:
                lines.append(f"\n**Mitigation:** {chain.mitigation}")
            if chain.references:
                lines.append("\n**References:**")
                for ref in chain.references:
                    lines.append(f"- {ref}")
            lines.append("\n---\n")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Markdown playbook written to %s", path)
        return path

    # ------------------------------------------------------------------
    # JSON
    # ------------------------------------------------------------------
    def write_json(self, path: Path) -> Path:
        """Write JSON report."""
        data = self._report.to_dict()
        path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
        logger.info("JSON report written to %s", path)
        return path

    # ------------------------------------------------------------------
    # Checklist Markdown
    # ------------------------------------------------------------------
    def write_checklist(self, path: Path) -> Path:
        """Write the vulnerability checklist as markdown."""
        r = self._report
        lines: list[str] = []
        lines.append(f"# Vulnerability Checklist: {r.target}")
        lines.append(f"\n> {len(r.applicable_checks)}/{len(r.checklist)} checks applicable based on recon findings\n")

        # Group by phase
        phases: dict[str, list[ChecklistItem]] = {}
        for item in r.checklist:
            if item.phase not in phases:
                phases[item.phase] = []
            phases[item.phase].append(item)

        for phase, items in phases.items():
            applicable = [i for i in items if i.applicable]
            lines.append(f"## {phase} ({len(applicable)}/{len(items)} applicable)")
            lines.append("")
            for item in items:
                mark = "x" if item.applicable else " "
                sev_tag = f"[{item.severity.upper()[0]}]"
                lines.append(f"- [{mark}] {sev_tag} {item.check}")
                if item.applicable and item.reason:
                    lines.append(f"  - *{item.reason}*")
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Checklist written to %s", path)
        return path

    # ------------------------------------------------------------------
    # HTML
    # ------------------------------------------------------------------
    def write_html(self, path: Path) -> Path:
        """Write a dark-themed HTML attack playbook."""
        r = self._report
        sev = r.severity_counts()
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        chains_html = []
        for i, chain in enumerate(r.chains, 1):
            sev_class = chain.severity
            steps_rows = "".join(
                f"<tr><td>{s.order}</td><td>{s.action}</td>"
                f"<td><code>{_esc(s.command[:120])}</code></td>"
                f"<td>{_esc(s.expected_result)}</td></tr>"
                for s in chain.steps
            )
            assets = "".join(f"<li><code>{_esc(a)}</code></li>" for a in chain.affected_assets[:5])
            refs = "".join(f'<li><a href="{r}" target="_blank">{_esc(r[:60])}</a></li>' for r in chain.references)

            chains_html.append(f"""
            <div class="chain {sev_class}">
                <div class="chain-header">
                    <span class="chain-num">#{i}</span>
                    <span class="sev-badge {sev_class}">{chain.severity.upper()}</span>
                    <h3>{_esc(chain.title)}</h3>
                    <span class="confidence">{chain.confidence:.0%} confidence</span>
                </div>
                <p class="desc">{_esc(chain.description)}</p>
                <div class="assets"><strong>Affected:</strong><ul>{assets}</ul></div>
                <table class="steps">
                    <thead><tr><th>#</th><th>Action</th><th>Command</th><th>Expected</th></tr></thead>
                    <tbody>{steps_rows}</tbody>
                </table>
                <div class="meta">
                    <p><strong>Tools:</strong> {', '.join(chain.tools_needed)}</p>
                    <p><strong>Mitigation:</strong> {_esc(chain.mitigation)}</p>
                    {"<p><strong>References:</strong></p><ul>" + refs + "</ul>" if refs else ""}
                </div>
            </div>""")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Attack Playbook - {_esc(r.target)}</title>
<style>
:root {{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#e6edf3;--muted:#8b949e;
--crit:#f85149;--high:#d29922;--med:#58a6ff;--low:#3fb950;}}
*{{margin:0;padding:0;box-sizing:border-box;}}
body{{background:var(--bg);color:var(--text);font-family:Inter,-apple-system,sans-serif;padding:2rem;}}
h1{{font-size:2rem;margin-bottom:.5rem;}}
.summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:1rem;margin:1.5rem 0;}}
.stat{{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem;text-align:center;}}
.stat .num{{font-size:2rem;font-weight:700;}}
.stat.critical .num{{color:var(--crit);}} .stat.high .num{{color:var(--high);}}
.stat.medium .num{{color:var(--med);}} .stat.low .num{{color:var(--low);}}
.chain{{background:var(--card);border:1px solid var(--border);border-radius:8px;margin:1.5rem 0;padding:1.5rem;}}
.chain.critical{{border-left:4px solid var(--crit);}} .chain.high{{border-left:4px solid var(--high);}}
.chain.medium{{border-left:4px solid var(--med);}} .chain.low{{border-left:4px solid var(--low);}}
.chain-header{{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap;margin-bottom:1rem;}}
.chain-num{{color:var(--muted);font-size:.9rem;}}
.sev-badge{{padding:2px 8px;border-radius:4px;font-size:.75rem;font-weight:700;color:#fff;}}
.sev-badge.critical{{background:var(--crit);}} .sev-badge.high{{background:var(--high);}}
.sev-badge.medium{{background:var(--med);}} .sev-badge.low{{background:var(--low);}}
.chain-header h3{{flex:1;font-size:1.1rem;}}
.confidence{{color:var(--muted);font-size:.85rem;}}
.desc{{color:var(--muted);margin-bottom:1rem;line-height:1.5;}}
.steps{{width:100%;border-collapse:collapse;margin:1rem 0;}}
.steps th,.steps td{{padding:.5rem .75rem;text-align:left;border-bottom:1px solid var(--border);font-size:.85rem;}}
.steps th{{color:var(--muted);font-weight:600;}}
.steps code{{background:#1c2128;padding:2px 6px;border-radius:4px;font-size:.8rem;word-break:break-all;}}
.meta{{color:var(--muted);font-size:.85rem;margin-top:.5rem;}}
.meta p{{margin:.3rem 0;}} .meta a{{color:var(--med);}}
.assets ul{{list-style:none;display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.3rem;}}
.assets li{{background:var(--bg);padding:2px 8px;border-radius:4px;font-size:.8rem;}}
.footer{{margin-top:2rem;padding-top:1rem;border-top:1px solid var(--border);color:var(--muted);font-size:.8rem;}}
</style>
</head>
<body>
<h1>Attack Playbook: {_esc(r.target)}</h1>
<p style="color:var(--muted);">Generated by ScoutX Attack Chain Engine | {ts}</p>
<div class="summary">
    <div class="stat"><div class="num">{len(r.chains)}</div><div>Total Chains</div></div>
    <div class="stat critical"><div class="num">{sev.get('critical',0)}</div><div>Critical</div></div>
    <div class="stat high"><div class="num">{sev.get('high',0)}</div><div>High</div></div>
    <div class="stat medium"><div class="num">{sev.get('medium',0)}</div><div>Medium</div></div>
    <div class="stat low"><div class="num">{sev.get('low',0)}</div><div>Low</div></div>
    <div class="stat"><div class="num">{len(r.applicable_checks)}/{len(r.checklist)}</div><div>Checklist</div></div>
</div>
{"".join(chains_html)}
<div class="footer">ScoutX v2.0 | Attack Chain Engine | {ts}</div>
</body></html>"""

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8")
        logger.info("HTML playbook written to %s", path)
        return path


def _esc(text: str) -> str:
    """HTML-escape a string."""
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))
